web:
  build: ./php/
  command: php -S 0.0.0.0:8000 -t /app
  links:
    - db
    - redis
  ports:
    - "8000:8000"
  volumes:
    - ./php/app:/app
db:
  image: mysql
  volumes:
      - ./mysql-data:/var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: myapp
redis:
  image: redis
  ports:
    - "6379:6379"